apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "auto-scale", "namespace": "", "kind": "DeploymentConfig"}]'
  labels:
    name: auto-scale-pipeline
  name: auto-scale-pipeline
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
        stage 'build'
        openshiftBuild(buildConfig: 'auto-scale', showBuildLogs: 'true')
        stage 'deploy'
        openshiftDeploy(deploymentConfig: 'auto-scale')
        openshiftScale(deploymentConfig: 'auto-scale',replicaCount: '2')
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
