apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "auto-scale", "namespace": "", "kind": "DeploymentConfig"}]'
    creationTimestamp: 2016-10-28T01:16:12Z
    labels:
      app: auto-scale
    name: auto-scale
    namespace: test-jenkins
    selfLink: /oapi/v1/namespaces/test-jenkins/buildconfigs/auto-scale
    uid: 1dceeae4-9cac-11e6-aaf3-fa163e01bb5f
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: auto-scale:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/ganrad/PHP-OSE-LoadTest.git
      type: Git
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: build-scripts/jenkins-pipeline.txt
      from:
        kind: ImageStreamTag
        name: php:5.6
        namespace: openshift
    triggers:
    - generic:
        secret: 2fe259da2498535c
      type: Generic
    - github:
        secret: 9ea47c4e4b2d2c5e
      type: GitHub
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: 2016-10-28T01:16:12Z
    generation: 1
    labels:
      app: auto-scale
    name: auto-scale
    namespace: test-jenkins
    selfLink: /oapi/v1/namespaces/test-jenkins/imagestreams/auto-scale
    uid: 1dcf313c-9cac-11e6-aaf3-fa163e01bb5f
  spec: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: 2016-10-28T01:16:12Z
    generation: 1
    labels:
      app: auto-scale
    name: auto-scale
    namespace: test-jenkins
    selfLink: /oapi/v1/namespaces/test-jenkins/deploymentconfigs/auto-scale
    uid: 1dcecd2c-9cac-11e6-aaf3-fa163e01bb5f
  spec:
    replicas: 1
    selector:
      deploymentconfig: auto-scale
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: auto-scale
          deploymentconfig: auto-scale
      spec:
        containers:
        - image: auto-scale:latest
          imagePullPolicy: Always
          name: auto-scale
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers: []
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
      openshift.io/host.generated: "true"
    creationTimestamp: 2016-10-28T01:16:13Z
    labels:
      app: auto-scale
    name: auto-scale
    namespace: test-jenkins
    selfLink: /oapi/v1/namespaces/test-jenkins/routes/auto-scale
    uid: 1dd37317-9cac-11e6-aaf3-fa163e01bb5f
  spec:
    host: auto-scale-test-jenkins.oscp.nilanet.com
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: auto-scale
      weight: 100
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: 2016-10-28T01:16:12Z
    labels:
      app: auto-scale
    name: auto-scale
    namespace: test-jenkins
    selfLink: /api/v1/namespaces/test-jenkins/services/auto-scale
    uid: 1dd1715b-9cac-11e6-aaf3-fa163e01bb5f
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: auto-scale
    sessionAffinity: None
    type: ClusterIP
kind: List
metadata: {}
